version: '3.8'

services:
  bloodhub:
    build: .
    ports:
      - "8050:8050"  # Dash application
      - "8000:8000"  # FastAPI
    volumes:
      - ./data:/app/data
      - ./assets:/app/assets
    environment:
      - DASH_DEBUG=False
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050"]
      interval: 30s
      timeout: 10s
      retries: 3